from selenium import webdriver
# from selenium.webdriver.common.by import By
import time
a=webdriver.Chrome()
a.maximize_window()
a.get("http://www.baidu.com")
a.find_element_by_name("wd").send_keys("QQ邮箱")
a.find_element_by_id("su").click()
time.sleep(3)
a.find_element_by_xpath("//*[@id='1']/div/div[1]/h3/a").click()
a.window_handles #获取所以窗口
a.switch_to.window(a.window_handles[-1]) #跳转索引[0]窗口
time.sleep(2)
a.switch_to.frame("login_frame")
a.find_element_by_id("img_out_245344724").click()
time.sleep(2)
a.find_element_by_id("composebtn").click()
time.sleep(2)
a.switch_to.frame("mainFrame")
a.find_element_by_id("toAreaCtrl").click()
time.sleep(2)
a.find_element_by_xpath("//*[@id='toAreaCtrl']/div[2]/input").send_keys("245344724@qq.com")
time.sleep(2)
a.find_element_by_id("subject").send_keys("好久不见")
time.sleep(2)
a.find_element_by_name("UploadFile").send_keys("C:\\Users\\EDY\\Desktop\\下载.jpg")
a.switch_to.frame(a.find_element_by_xpath("/html/body/form[2]/div[2]/div[7]/table/tbody/tr/td[2]/div/table/tbody/tr[2]/td/iframe"))
a.find_element_by_xpath("/html/body").send_keys("你在哪里")
a.switch_to.parent_frame()
time.sleep(2)
a.find_element_by_name("sendbtn").click()
time.sleep(5)
a.quit()